In [ ]:
import pandas as pd

In [ ]:
! pip install datasets

Collecting datasets
  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.30.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.5.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 8.9 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 7.3 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 10.1 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 9.6 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 12.5 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2024.12.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.5.0 dill-0.3.8 fsspec-2024.12.0 multiprocess-0.70.16 xxhash-3.5.0

In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset('lukebarousse/data_jobs')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [ ]:
df= dataset['train'].to_pandas()

In [ ]:
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [ ]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [ ]:
df['salary_year_avg'].min()

15000.0

In [ ]:
min_salary = df['salary_year_avg'].idxmin()

In [ ]:
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [ ]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [ ]:
df.groupby(['job_title_short','job_country'])['salary_year_avg'].median()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      71100.0
                                   ...
Software Engineer  Venezuela          NaN
                   Vietnam        53600.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

In [ ]:
df.groupby('job_title_short')[['salary_year_avg','salary_hour_avg']].agg(['min','max'])

                          salary_year_avg           salary_hour_avg
                                      min       max             min    max
job_title_short
Business Analyst                  16500.0  387460.0          10.835  132.5
Cloud Engineer                    42000.0  280000.0          18.500   91.0
Data Analyst                      25000.0  650000.0           8.000  391.0
Data Engineer                     15000.0  525000.0           8.000  184.5
Data Scientist                    27000.0  960000.0           8.000  237.5
Machine Learning Engineer         30000.0  325000.0          10.000   87.5
Senior Data Analyst               30000.0  425000.0          13.000  130.0
Senior Data Engineer              35000.0  425000.0          12.500  170.0
Senior Data Scientist             45000.0  890000.0          17.500  150.0
Software Engineer                 28000.0  375000.0          11.000  102.5

In [ ]:
df['job_country'].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [ ]:
df['job_country'].isin(['Kongo']).any()

np.False_

In [ ]:
pol = df[df.job_country =='Poland']

In [ ]:
pol

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
18,Data Analyst,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-10-16 13:36:54,False,False,Poland,None,NaN,NaN,Glovo,"['sql', 'python', 'r', 'redshift', 'pandas', '...","{'analyst_tools': ['excel', 'looker', 'tableau..."
108,Data Engineer,Chapter Lead Data Engineers Poland,"Wrocław, Poland",via Trabajo.org,Full-time,False,Poland,2023-01-16 13:58:03,False,False,Poland,None,NaN,NaN,Volvo Group,"['azure', 'excel', 'unity']","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
125,Data Engineer,Data Engineer,"Kraków, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-06-04 14:12:20,True,False,Poland,None,NaN,NaN,SII Group,"['sql', 'shell', 'python', 'aws']","{'cloud': ['aws'], 'programming': ['sql', 'she..."
136,Data Scientist,Mid/ Senior Data Scientist with NLP,Anywhere,via LinkedIn,Full-time,True,Poland,2023-12-21 13:10:55,False,False,Poland,None,NaN,NaN,Trans.eu Group,"['python', 'sql', 'snowflake', 'aws', 'scikit-...","{'cloud': ['snowflake', 'aws'], 'libraries': [..."
351,Software Engineer,Data Platform Software Engineer,"Warsaw, Poland",via Adzuna.pl,Full-time,False,Poland,2023-06-23 13:58:41,True,False,Poland,None,NaN,NaN,IBM,"['python', 'sql', 'shell', 'ibm cloud', 'linux']","{'cloud': ['ibm cloud'], 'os': ['linux'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785549,Data Scientist,Data Scientist,"Warsaw, Poland",via Trabajo.org,Full-time,False,Poland,2023-01-13 06:41:55,False,False,Poland,None,NaN,NaN,Citi,"['python', 'r']","{'programming': ['python', 'r']}"
785592,Senior Data Analyst,VP - Institutional Credit Management - Lending...,"Warsaw, Poland",via Trabajo.org,Full-time,False,Poland,2023-01-13 06:41:53,True,False,Poland,None,NaN,NaN,Citi,None,None
785650,Software Engineer,Integration Analyst,"Łódź, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-04-26 06:24:52,False,False,Poland,None,NaN,NaN,Team Quest,"['sql', 'oracle', 'aws', 'sap', 'atlassian']","{'analyst_tools': ['sap'], 'cloud': ['oracle',..."
785669,Machine Learning Engineer,Senior Machine Learning Engineer,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-06-07 06:18:29,False,False,Poland,None,NaN,NaN,Digital Hub Warsaw At Bayer,"['python', 'aws', 'gcp', 'azure', 'tensorflow'...","{'cloud': ['aws', 'gcp', 'azure'], 'libraries'..."
785702,Business Analyst,Aeronautical Analyst,"Gdańsk, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-04-26 06:24:52,False,False,Poland,None,NaN,NaN,NAVBLUE,None,None

In [ ]:
df[df.job_country =='Poland']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
18,Data Analyst,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-10-16 13:36:54,False,False,Poland,None,NaN,NaN,Glovo,"['sql', 'python', 'r', 'redshift', 'pandas', '...","{'analyst_tools': ['excel', 'looker', 'tableau..."
108,Data Engineer,Chapter Lead Data Engineers Poland,"Wrocław, Poland",via Trabajo.org,Full-time,False,Poland,2023-01-16 13:58:03,False,False,Poland,None,NaN,NaN,Volvo Group,"['azure', 'excel', 'unity']","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
125,Data Engineer,Data Engineer,"Kraków, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-06-04 14:12:20,True,False,Poland,None,NaN,NaN,SII Group,"['sql', 'shell', 'python', 'aws']","{'cloud': ['aws'], 'programming': ['sql', 'she..."
136,Data Scientist,Mid/ Senior Data Scientist with NLP,Anywhere,via LinkedIn,Full-time,True,Poland,2023-12-21 13:10:55,False,False,Poland,None,NaN,NaN,Trans.eu Group,"['python', 'sql', 'snowflake', 'aws', 'scikit-...","{'cloud': ['snowflake', 'aws'], 'libraries': [..."
351,Software Engineer,Data Platform Software Engineer,"Warsaw, Poland",via Adzuna.pl,Full-time,False,Poland,2023-06-23 13:58:41,True,False,Poland,None,NaN,NaN,IBM,"['python', 'sql', 'shell', 'ibm cloud', 'linux']","{'cloud': ['ibm cloud'], 'os': ['linux'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785549,Data Scientist,Data Scientist,"Warsaw, Poland",via Trabajo.org,Full-time,False,Poland,2023-01-13 06:41:55,False,False,Poland,None,NaN,NaN,Citi,"['python', 'r']","{'programming': ['python', 'r']}"
785592,Senior Data Analyst,VP - Institutional Credit Management - Lending...,"Warsaw, Poland",via Trabajo.org,Full-time,False,Poland,2023-01-13 06:41:53,True,False,Poland,None,NaN,NaN,Citi,None,None
785650,Software Engineer,Integration Analyst,"Łódź, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-04-26 06:24:52,False,False,Poland,None,NaN,NaN,Team Quest,"['sql', 'oracle', 'aws', 'sap', 'atlassian']","{'analyst_tools': ['sap'], 'cloud': ['oracle',..."
785669,Machine Learning Engineer,Senior Machine Learning Engineer,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-06-07 06:18:29,False,False,Poland,None,NaN,NaN,Digital Hub Warsaw At Bayer,"['python', 'aws', 'gcp', 'azure', 'tensorflow'...","{'cloud': ['aws', 'gcp', 'azure'], 'libraries'..."
785702,Business Analyst,Aeronautical Analyst,"Gdańsk, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-04-26 06:24:52,False,False,Poland,None,NaN,NaN,NAVBLUE,None,None

In [ ]:
pol = pol.dropna(subset='salary_year_avg')

In [ ]:
pol.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1490 to 783448
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        200 non-null    object
 1   job_title              200 non-null    object
 2   job_location           200 non-null    object
 3   job_via                200 non-null    object
 4   job_schedule_type      200 non-null    object
 5   job_work_from_home     200 non-null    bool
 6   search_location        200 non-null    object
 7   job_posted_date        200 non-null    datetime64[ns]
 8   job_no_degree_mention  200 non-null    bool
 9   job_health_insurance   200 non-null    bool
 10  job_country            200 non-null    object
 11  salary_rate            200 non-null    object
 12  salary_year_avg        200 non-null    float64
 13  salary_hour_avg        0 non-null      float64
 14  company_name           200 non-null    object
 15  job_skills             191 non-null    object
 16  job_type_skills        191 non-null    object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 24.0+ KB

In [ ]:
pol.groupby('job_title_short')[['salary_year_avg']].agg(['min','max','median','count']).sort_values(('salary_year_avg', 'median'), ascending = False)

                          salary_year_avg
                                      min       max    median count
job_title_short
Senior Data Scientist             88128.0  157500.0  157500.0    12
Data Engineer                     45000.0  164500.0  133500.0    46
Data Scientist                    43200.0  186928.0  131867.0    29
Senior Data Analyst               86400.0  119400.0  111175.0     9
Machine Learning Engineer         56700.0  186000.0   89100.0    23
Data Analyst                      43200.0  165000.0   89100.0    43
Senior Data Engineer              45000.0  147500.0   89100.0     9
Software Engineer                 65769.0  156500.0   89100.0    15
Business Analyst                  56700.0  153500.0   87050.0     8
Cloud Engineer                    56700.0  221000.0   84150.0     6